### ISSUE TITLE
incorrect command line

### ISSUE THREAD

**Issue by jicheu** [canonical-web-and-design/microstack.run#170]
## Summary

Incorrect command

## Process

go to https://microstack.run/#get-started
click on MacOS

## Current and expected result

Step 4:
the command listed is:
`sudo microstack init --auto --control  `
it should be:
`multipass exec microstack-vm -- sudo microstack init --auto --control  `

**Comment by jicheu** [comment]
It's actually the same for the next two commands

**Comment by cristinadresch** [comment]
@pmatulis could you have a look at this one please

**Comment by pmatulis** [comment]
@cristinadresch I'm not familar with running MicroStack on macOS. If you can confirm exactly what needs to be changed then I can go ahead and implement a fix.

**Comment by jicheu** [comment]
@pmatulis give a look to the original post, if that's not clear enough let me know how I can help

**Comment by carkod** [comment]
@jicheu At the bottom of the page, you have a link to "Help improve this documentation". Can you click on that link and post on this suggestion in the corresponding discourse topic? This is the repo of the website, so the documentation authors don't usually come here to answer. Thank you.
