### ISSUE TITLE
con,t create instances 

### ISSUE THREAD

**Issue by yeesupadit** [canonical-web-and-design/microstack.run#172]
Error: Failed to perform requested operation on instance "ubuntu 20.04", the instance has an error status: Please try again later [Error: Build of instance b013d701-513f-4ea8-b3b2-3561e5065a3d aborted: Invalid input received: Invalid image identifier or unable to access requested image. (HTTP 400) (Request-ID: req-55fd389d-fec5-451a-9384-73102c8ccd71)].

**Comment by pmahnke** [comment]
@yeesupadit you filed the bug against the website.  For bugs in the programme, can you refile it here? https://bugs.launchpad.net/microstack/+filebug  thanks.

Closing.
