### ISSUE TITLE
microstack.run should suggest installing --beta version of snap, rather than --edge

### ISSUE THREAD

**Issue by petevg** [canonical-web-and-design/microstack.run#28]
## Summary

As of this week, it is a much better idea to install the --beta snap, instead of the --edge snap. Edge is currently a strictly confined snap that must be run in devmode. There are sharp edges.

Meanwhile, the beta has been updated with what was in edge prior to this week. It has clustering and other features that the site mentions, and that users might want to try. 

## Process

Replace --edge in the Linux, Windows and OSX install instructions with --beta.

## Current and expected result

The site will recommend installing from --beta rather than --edge.

**Comment by pmahnke** [comment]
@petevg where are you seeing 'edge'  I only see it on the /docs pages.

```
ag "\-\-edge"
docs/index.md
46:sudo snap install microstack --devmode --edge

docs/clustering.md
27:    At this time, clustering requires the snap installation to use the `--edge`
```

**Comment by petevg** [comment]
I think that I must have had a cached version of the page in my browser. As of today, I see beta everywhere I expect to see beta. Apologies for the redundant bug!
