### ISSUE TITLE
Reinstallation issue

### ISSUE THREAD

**Issue by muhammad-waqar-ivolve** [canonical-web-and-design/microstack.run#32]
## Summary
I install the microstack with $sudo microstack.init --auto but it says you are unauthorized
I have microstack installed but only identity service is running and i am unable to create instance

![Screenshot from 2020-03-26 15-18-41](https://user-images.githubusercontent.com/59274470/77636003-3e948900-6f75-11ea-8d9f-c3b0892706de.png)

**Comment by SirSamTumless** [comment]
Hi, thanks for flagging this. Could you please report this issue on https://discourse.juju.is/search?q=microstack. This is the repo for microstack.run website, not the project itself.

Cheers,
Sam
